# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }} | ${matrix.config.compiler || "default"})

    strategy:
      fail-fast: false
      matrix:
          config:
          # Windows
          - {os: windows-latest, r: 'release'}
          # Ubuntu
          - {os: ubuntu-latest, r: 'devel', compiler: 'gcc'}
          - {os: ubuntu-latest, r: 'devel', compiler: 'clang'}
          - {os: ubuntu-latest, r: 'release', compiler: 'gcc'}
          - {os: ubuntu-latest, r: 'release', compiler: 'clang'}
          - {os: ubuntu-latest, r: 'oldrel-1', compiler: 'gcc'}
          # Fedora (via container)
          - {os: ubuntu-latest, r: 'devel', container: 'rocker/r-devel-fedora:38', compiler: 'gcc'}
          - {os: ubuntu-latest, r: 'release', container: 'rocker/r-release-fedora:38', compiler: 'gcc'}
          # Debian (via container)
          - {os: ubuntu-latest, r: 'devel', container: 'rocker/r-devel-debian:bookworm', compiler: 'gcc'}
          - {os: ubuntu-latest, r: 'release', container: 'rocker/r-release-debian:bookworm', compiler: 'gcc'}


    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up container (if specified)
        if: matrix.config.container != null
        run: echo "Using container ${{ matrix.config.container }}"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Switch compiler (Linux only)
        if: matrix.config.compiler != null && runner.os != 'Windows'
        run: |
          if [ "${{ matrix.config.compiler }}" = "clang" ]; then
            echo "Using Clang"
            sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
            sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
          else
            echo "Using GCC"
            sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 100
            sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 100
          fi

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
